name: Create Weekly Retrospective page

on:
  # For automation
  schedule:
    # 09:00 Friday CDT, 08:00 Friday CST
    - cron: "00 14 * * 5"

jobs:
  weekly-retrospective-confluence:
    runs-on: ubuntu-latest

    env:
      KEY_USERNAME: ${{ secrets.USERNAME_AMADEUS }}
      KEY_TOKEN: ${{ secrets.TOKEN_AMADEUS }}

    steps:
      - uses: actions/checkout@v4

      - name: Set Python up
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip && python -m pip install -r requirements.txt

      - name: Run script
        run: python weekly_retrospective_confluence.py
